# Generated by Django 5.2 on 2025-05-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop'), ('MOBILE', 'Mobile'), ('TABLET', 'Tablet'), ('PRINTER', 'Printer'), ('SCANNER', 'Scanner'), ('PROJECTOR', 'Projector')], max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assignee',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('WORKING', 'Working'), ('SOFTWARE_ISSUE', 'Software-issue'), ('HARDWARE_ISSUE', 'Hardware-issue'), ('DAMAGED', 'Damaged')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='operating_system',
            field=models.CharField(choices=[('WINDOWS', 'Windows'), ('MACOS', 'macOS'), ('LINUX', 'Linux'), ('ANDROID', 'Android'), ('IOS', 'iOS'), ('CHROMEOS', 'ChromeOS'), ('HYPEROS', 'HyperOS'), ('OTHER', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('AVAILABLE', 'Available'), ('IN_REPAIR', 'In-repair'), ('UNDER_MAINTENANCE', 'Under-maintenance'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=20),
        ),
    ]
