# Generated by Django 5.2 on 2025-05-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_asset_type_alter_asset_processor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop'), ('MOBILE', 'Mobile'), ('TABLET', 'Tablet'), ('PRINTER', 'Printer'), ('SCANNER', 'Scanner'), ('PROJECTOR', 'Projector'), ('SERVER', 'Server'), ('NETWORK_DEVICE', 'Network Device'), ('MONITOR', 'Monitor'), ('SCREEN', 'Screen'), ('TV', 'TV'), ('ROBOTS', 'Robots'), ('UPS', 'UPS'), ('EXTERNAL_DRIVE', 'External Drive'), ('OTHER', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('WORKING', 'Working'), ('SOFTWARE_ISSUE', 'Software-issue'), ('HARDWARE_ISSUE', 'Hardware-issue'), ('DAMAGED', 'Damaged')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('AVAILABLE', 'Available'), ('IN_REPAIR', 'In-repair'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=20),
        ),
    ]
